// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://geenpscbnvbwyvmlybom.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdlZW5wc2NibnZid3l2bWx5Ym9tIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMDgzODcsImV4cCI6MjA3NzU4NDM4N30.6OyHMrihEpPfr5Q4vR08TcXRPfhhkKCS8SWPO54ybSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});